### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【内测反馈】【内核】【6.4.7】升级最新版内核后,yoga 的内置键盘无法使用

### ISSUE THREAD

**Issue by vivianxf** [deepin-community/kernel#14]
【配置】:
 镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核:6.4.7

【复现步骤】:
  1.系统内核升级到6.4.7
  2.正常使用yoga 的内置键盘操作
  3.观察使用情况

【观察到的结果】:
  1.yoga 的内置键盘无法使用

【期望的结果】:
  1.yoga 的内置键盘可以正常使用

**Comment by xzl01** [comment]
https://github.com/torvalds/linux/commit/936e4d49ecbc8c404790504386e1422b599dec39

**Comment by xzl01** [comment]
此问题在主线已经得到解决 可以回归关闭

**Comment by babyfengfjx** [comment]
@vivianxf  请在最新版本内核中回归验证。

**Comment by kobe337** [comment]
目前内核已经更新至6.6.38，经过内测版本迭代，未收到使用联想yoga用户的问题反馈，此问题与研发同事进行沟通，得知相关修复patch已经合入，此issue关闭
