### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【内测反馈】【内核】 6.6.35版本hwe内核更新导致broadcom-sta-dkms博通无线网卡驱动编译失败

### ISSUE THREAD

**Issue by xuqi27837288** [deepin-community/kernel#304]
###  SUMMARY | 问题概要
必现问题

[make.log](https://github.com/user-attachments/files/16047567/make.log)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240628/
内核：Linux deepinrc2-PC 6.6.35-amd64-desktop-hwe 

###  PRE-REQUIREMENT | 预置条件
No response

### STEPS TO REPRODUCE | 复现步骤
更新至0628内测环境,观察 6.6.35版本hwe内核下博通无线网卡驱动是否可以正常运行

### OBSERVED RESULT | 观察到的结果
6.6.35版本hwe内核更新导致broadcom-sta-dkms博通无线网卡驱动编译失败

### EXPECTED RESULT | 期望的结果
6.6.35版本hwe内核下broadcom-sta-dkms博通无线网卡驱动可以正常运行

**Comment by babyfengfjx** [comment]
@MingcongBai  这个说是在6.6.36版本会由你这边处理，处理完成后，可以提测并走给测试确认。

**Comment by MingcongBai** [comment]
> @MingcongBai 这个说是在6.6.36版本会由你这边处理，处理完成后，可以提测并走给测试确认。

今日推送 6.6.36 (23.01.00.28) 应该可以修复此问题

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/
仓库：提测单仓库 https://github.com/linuxdeepin/developer-center/issues/9497
内核：Linux deepin 6.6.36-amd64-desktop-hwe #23.01.00.29 SMP PREEMPT_DYNAMIC Tue Jul  2 13:48:43 CST 2024 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响

https://github.com/linuxdeepin/developer-center/issues/9497 提测单回归验证通过，安装broadcom-sta-dkms成功。
![broadcom-sta-dkms](https://github.com/deepin-community/kernel/assets/17869922/2c98a83b-499d-4467-beb9-f9fd8d05c2b6)
