### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【发散测试】【内核】【6.6.36-amd64】ThinkBook 14 G4+ ARA设备安装系统黑屏

### ISSUE THREAD

**Issue by kobe337** [deepin-community/kernel#319]
### SUMMARY | 问题概要

ThinkBook 14 G4+ ARA设备安装系统黑屏（amdgpu）

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：[deepin-23-beige-rc2-amd64-20240710-143823](https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240710/)
内核：Linux deepin-PC 6.6.36-amd64-desktop-hwe #23.01.00.29 SMP PREEMPT_DYNAMIC Tue Jul  2 13:48:43 CST 2024 x86_64 GNU/Linux
```
[设备信息]
-------------------------------------------------
设备:                  LENOVO 21D0 (LENOVO_MT_21D0_BU_idea_FM_ThinkBook 14 G4+ ARA) Notebook 
操作系统:                Deepin 23 Community(RC2) Linux version 6.6.25-amd64-desktop-hwe (deepin@v23.deepinci-amd4) (gcc (Deepin 13.2.0-3deepin) 13.2.0, GNU ld (GNU Binutils for Deepin) 2.41) #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024
处理器:                 AMD Ryzen 7 6800H with Radeon Graphics (八核 / 十六逻辑处理器)
主板:                  LNVNB161216
内存:                  4GB(MT62F1G32D4DR-031 WT  6400 MT/s)/4GB(MT62F1G32D4DR-031 WT  6400 MT/s)/4GB(MT62F1G32D4DR-031 WT  6400 MT/s)/4GB(MT62F1G32D4DR-031 WT  6400 MT/s)
显示适配器:               GA107M [GeForce RTX 2050]/Rembrandt [Radeon 680M]
音频适配器:               Family 17h/19h HD Audio Controller/Rembrandt Radeon High Definition Audio Controller
存储设备:                SAMSUNG MZVL2512HCJQ-00BL2 (512 GB)/ZhenJBfast (64GB)
蓝牙:                  deepin
网络适配器:               RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller/RTL8852BE PCIe 802.11ax Wireless Network Controller
鼠标:                  ELAN0662:00 04F3:317C Mouse (ELAN0662:00 04F3:317C Mouse)/ELAN0662:00 04F3:317C Touchpad (ELAN0662:00 04F3:317C Touchpad)
键盘:                  AT Translated Set 2 keyboard (AT Translated Set 2 keyboard)
显示设备:                Generic Monitor()
图像设备:                Integrated RGB Camera (Bison Electronics Integrated RGB Camera)

### PRE-REQUIREMENT | 预置条件
使用U盘刻录镜像
_No response_

### STEPS TO REPRODUCE | 复现步骤

1. 通过刻录好的镜像安装系统，观察安装过程
### OBSERVED RESULT | 观察到的结果
ThinkBook 14 G4+ ARA设备安装系统黑屏
![56548bfdc7c1920648052f025f8ee02c](https://github.com/deepin-community/kernel/assets/17869922/c0d758dd-be02-4c1d-8037-81e3b5a4c97e)

### EXPECTED RESULT | 期望的结果

1. ThinkBook 14 G4+ ARA设备安装系统成功

**Comment by babyfengfjx** [comment]
@Zeno-sole  请优先分析~

**Comment by Avenger-285714** [comment]
该问题已修复https://github.com/deepin-community/kernel/pull/320

**Comment by kobe337** [comment]
【环境】：
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240711/deepin-23-beige-rc2-amd64-20240711-220705.iso
仓库：https://github.com/linuxdeepin/developer-center/issues/9653 提测单仓库
内核：Linux deepin-PC 6.6.38-amd64-desktop-hwe #23.01.00.30 SMP PREEMPT_DYNAMIC Thu Jul 11 17:19:00 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响,  安装校验、版本核对，覆盖内核6.6.38 与6.9.6 均能正常安装与进入桌面，验证通过
![azyxf](https://github.com/user-attachments/assets/ee543060-11fd-4308-bd3a-a193b6caff40)
