### ISSUE TITLE
UOS-K5.10-LTS branch 在 arm64 CPU 下，无法编译成功

### ISSUE THREAD

**Issue by atzlinux** [deepin-community/kernel#4]
drm 下的 飞腾 模块 drivers/gpu/drm/phytium ，编译报错，提示找不到 drmP.h 文件。

**Comment by BLumia** [comment]
这个是 v23 的仓库版本，不是适用于现有商业 UOS 版本的仓库。商业 UOS 版本相关的问题建议走 UOS 相关的渠道反馈哈。

**Comment by rtlhq** [comment]
若果设备带独显，可以不编译 phytium 的图形驱动来绕过这个错误

**Comment by zhanjun198510** [comment]
X100的代码在K5.10还有问题，可以先关闭配置。
