### ISSUE TITLE
【deepin_V23_beta3】【一般】【正常】【预发布测试】【内核】【6.6.7】联想小新16更新至内核至6.6.7后，无线网络模块不可用

### ISSUE THREAD

**Issue by xuqi27837288** [deepin-community/kernel#46]
SOFTWARE/OS VERSIONS | 软件/系统版本信息
1. 镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
2. 内核：Linux deepin-PC 6.6.7-amd64-desktop-hwe #23.01.00.21 SMP PREEMPT_DYNAMIC Fri Dec 15 10:50:06 CST 2023 x86_64 GNU/Linux

[概况]
-------------------------------------------------
设备:                  LENOVO 82XF (LENOVO_MT_82XF_BU_idea_FM_XiaoXin 16 IRL8) Notebook 
操作系统:                Deepin 23 Community(Beta3) Linux version 6.6.7-amd64-desktop-hwe (deepin@v23.deepinci-amd4) (gcc (Deepin 13.2.0-3deepin) 13.2.0, GNU ld (GNU Binutils for Deepin) 2.41) #23.01.00.21 SMP PREEMPT_DYNAMIC Thu Dec 14 17:07:54 CST 2023
处理器:                 13th Gen Intel(R) Core(TM) i5-1340P (十二核 / 十六逻辑处理器)
主板:                  LNVNB161216
内存:                  8GB(K3LKBKB@BM-MGCP  6400 MT/s)/8GB(K3LKBKB@BM-MGCP  6400 MT/s)
显示适配器:               Raptor Lake-P [Iris Xe Graphics]
音频适配器:               Intel Corporation
存储设备:                UMIS RPEYJ1T24MKN2QWY (1.00 TB)
蓝牙:                  Bluetooth Radio
网络适配器:               RTL8153 Gigabit Ethernet Adapter
鼠标:                  Optical Mouse (Pixart Imaging Optical Mouse)/MSFT0002:00 06CB:CEFE Mouse (MSFT0002:00 06CB:CEFE Mouse)/MSFT0002:00 06CB:CEFE Touchpad (MSFT0002:00 06CB:CEFE Touchpad)
键盘:                  AT Translated Set 2 keyboard (AT Translated Set 2 keyboard)
显示设备:                CSOT T3 LCD Monitor(16.0 英寸(344mm X 215mm))
图像设备:                Integrated RGB Camera (Luxvisions Innotech Integrated RGB Camera)

-------------------------------------------------

PRE-REQUIREMENT | 预置条件

STEPS TO REPRODUCE | 复现步骤

1.进入桌面环境，观察无线网络是否正常可用

OBSERVED RESULT | 观察到的结果
无法使用

![微信图片_20231228135533](https://github.com/deepin-community/kernel/assets/62528742/4f40131e-ca11-4e01-9652-3be2adedda02)

EXPECTED RESULT | 期望的结果
可以正常使用

**Comment by matrix-wsk** [comment]
更新 kernel 6.6.21 已解决

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
